In [3]:
import pandas as pd
import sklearn
import numpy as np
#read file
df1=pd.read_csv("EY1.csv")
df2=pd.read_csv("EY2.csv")


In [4]:
def convert_to_days(date):
    su = date.split('/')
    return int(su[0]) + (int(su[1])*30) + (int(su[2])*365)
    #return int(st[0]) + (int(st[1])*30)

#convert date to numerical value for distance calculation

for i in range(0,len(df1)):
    df1['Trade_date'][i] = convert_to_days(df1['Trade_date'][i])
    df1['Settle_date'][i] = convert_to_days(df1['Settle_date'][i])

#convert date to numerical value for distance calculation
for i in range(0,len(df2)):
    df2['Trade_date'][i] = convert_to_days(df2['Trade_date'][i])
    df2['Settle_date'][i] = convert_to_days(df2['Settle_date'][i])



/home/schoolboy/miniconda2/lib/python2.7/site-packages/ipykernel/__main__.py:9: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/schoolboy/miniconda2/lib/python2.7/site-packages/ipykernel/__main__.py:10: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/schoolboy/miniconda2/lib/python2.7/site-packages/ipykernel/__main__.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/home/schoolboy/miniconda2/lib/python2.7/site-packages/ipykernel/__main__.py:15: SettingWithCopyWarning: 
A value is

In [5]:
#data format
df1.describe()

Time  Underlying ISIN  Trade_Amount
count  42.000000              0.0     42.000000
mean    4.285714              NaN  44505.000000
std     2.003481              NaN  19514.381876
min     3.000000              NaN  12000.000000
25%     3.000000              NaN  32980.250000
50%     3.000000              NaN  43227.000000
75%     5.000000              NaN  54000.000000
max    11.000000              NaN  98695.000000

In [7]:
#data format
df2.describe()

Time  Underlying ISIN  Trade_Amount
count  42.000000              0.0     42.000000
mean    4.285714              NaN  44505.000000
std     2.003481              NaN  19514.381876
min     3.000000              NaN  12000.000000
25%     3.000000              NaN  32980.250000
50%     3.000000              NaN  43227.000000
75%     5.000000              NaN  54000.000000
max    11.000000              NaN  98695.000000

In [8]:
dataset_array1 = df1.values

dataset_array2 = df2.values

sm1= np.delete(dataset_array1, [0,1,4,5,6,7,8,10], axis=1)
print(sm1.dtype)
print(sm1)
sm2= np.delete(dataset_array2, [0,1,4,5,6,7,8,10], axis=1)
print(sm2.dtype)
print(sm2)

a = np.array(sm1)
b = np.array(sm2)
dist = np.linalg.norm(a-b)
print(np.array(dist))

a = np.array(sm1)
b = np.array(sm2)
dist = np.linalg.norm(a-b)


#Euclidean distance function
def cal_distance(x,y):
    return np.sqrt(np.dot(x, x) - 2 * np.dot(x, y) + np.dot(y, y))
    

dist = []
for i in a:
    each_dist = []
    for j in b:
        each_dist.append(cal_distance(i, j))
    dist.append(each_dist)



object
[[6236 6247 50700]
 [5992 5995 72500]
 [5993 5996 64000]
 [5994 5997 39000]
 [5995 5998 45000]
 [5996 5999 12000]
 [5997 6000 54000]
 [5998 6001 62000]
 [5999 6002 54000]
 [6030 6038 12500]
 [6031 6036 43220]
 [6032 6037 43200]
 [6033 6038 23400]
 [6034 6039 53465]
 [6035 6040 34523]
 [6036 6041 43234]
 [6037 6042 23232]
 [6098 6101 53343]
 [6099 6102 54345]
 [6100 6103 66765]
 [6101 6104 23467]
 [6237 6248 34534]
 [5993 5996 64564]
 [5994 5997 76576]
 [5995 5998 23543]
 [5996 5999 98695]
 [5997 6000 34534]
 [5998 6001 23423]
 [5999 6002 64546]
 [6000 6003 46546]
 [6031 6039 23465]
 [6032 6037 45365]
 [6033 6038 23466]
 [6034 6039 34563]
 [6035 6040 24557]
 [6036 6041 34537]
 [6037 6042 32466]
 [6038 6043 53564]
 [6099 6102 45625]
 [6100 6103 87567]
 [6101 6104 34525]
 [6102 6105 34655]]
object
[[6236 6247 50700]
 [5992 5995 72500]
 [5993 5996 64000]
 [5994 5997 39000]
 [5995 5998 45000]
 [5996 5999 12000]
 [5997 6000 54000]
 [5998 6001 62000]
 [5999 6002 54000]
 [6030 6038 1250

In [9]:
z=dist[0]
print (z)
z=dist[1]
print (z)
z=dist[2]
print (z)
z=dist[3]
print (z)
z=dist[4]
print (z)
z=dist[0][1]
print (z)


[0.0, 21802.821835716586, 13304.587554674516, 11705.17253183395, 5710.52379383888, 38701.538780777177, 3317.8502075892457, 11305.182882200535, 3317.5584395757069, 38201.127169234154, 7485.7829249852011, 7505.7122246992658, 27301.55471763467, 2780.1606068714809, 16179.572893003078, 7471.5187211168786, 27469.485797881254, 2650.624266092801, 3650.4546292208593, 16066.220993127165, 27233.710048394067, 16166.000061858222, 13868.40098929938, 25878.339204825337, 27159.210794866627, 47996.240779877749, 16169.653243035238, 27279.147512339896, 13850.195305482157, 4167.8469261718337, 27236.565752678878, 5343.027325402707, 27235.558485186237, 16139.604611018201, 26144.592155931598, 16165.549944248727, 18236.238153742124, 2878.0750511409533, 5078.9190779141181, 36867.532070915731, 16176.195442686763, 16046.18786503511]
[21802.821835716586, 0.0, 8500.0001176470578, 33500.000119402983, 27500.000327272726, 60500.000264462811, 18500.0013513513, 10500.003428570868, 18500.00264864846, 60000.027441660393,

In [13]:

for i in range(0,len(dist)):
    # REMOVING 0 CUZ IT THE DISTANCE BETWEEN THE SAME DATA POINT
    new_data = filter(lambda a: a != 0, dist[i])
    print min(new_data)

2650.62426609
4076.00098135
546.065930085
4200.36236532
368.937664111
502.669871785
2.82842712475
2000.01249996
2.82842712475
502.669871785
15.6843871414
20.0499376558
55.8838080306
99.1614844584
14.0712472795
15.6843871414
168.095211116
151.076139744
372.86056375
2206.19559423
94.7681381056
198.275061468
19.8997487421
4076.00098135
94.7259204231
11128.9719202
56.2583327161
55.8838080306
19.8997487421
931.58091436
2.44948974278
276.249886878
2.44948974278
26.1533936612
1015.65742256
14.0712472795
2057.00194458
99.1614844584
276.249886878
10992.0222434
91.3126497261
130.00769208
